import argparse

class SrtScripter():
    """
    Generic SRT scripter with common functions for SRT operation.
    """
    def __init__(self):
        self.parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
        self.parser.add_argument("-o", "--output", type=str, default="script.cmd",
            help="The script file name generated by the scripter.")
        self.parser.add_argument("-r", "--rad", type=str, default="",
            help="Name of the .rad file where the script with write the measured data.")
        self.parser.parse_args()

SrtScripter()
